spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  mvc:
    static-locations: classpath:/templates/,classpath:/static/
    static-path-pattern: /*
mybatis:
  mapper-locations: classpath:mappers/*.xml
logging:
  level:
    com: debug #默认info等级
